# GOLANG CONFIGURATION
[[language]]
name = "go"
formatter = { command = "goimport" }


[language-server.gopls]
command = "gopls"
args = ["-logfile=/tmp/gopls.log",  "serve"]
[language-server.gopls.config]
"ui.diagnostic.staticcheck" = true

[language-server.gopls.config.hints]
assignVariableTypes = true
constantValues = true
functionTypeParameters = true
parameterNames = true
rangeVariableTypes = true

# PYTHON CONFIGURATION
[[language]]
name = "python"
comment-token = "#"
language-servers = [ "pylsp" ]

# TYPESCRIPT/JS/REACT/ANYTHING JAVASCRIPT
[language-server.typescript-language-server]
command = "typescript-language-server"
args = ["--stdio"]
config.hostInfo = "helix"

[[language]]
name = "typescript"
injection-regex = "(ts|typescript)"
language-id = "typescript"
language-servers = [ "typescript-language-server" ]
grammar = "typescript"

[[language]]
name = "javascript"
injection-regex = "(js|javascript)"
language-id = "javascript"
comment-token = "//"
language-servers = [ "typescript-language-server" ]
grammar = "javascript"

# SVELTE CONFIGURATION
#[[language]]
#name = "svelte"
#language-servers = ["svelte-language-server"]

# REACT CONFIGURATION
[[language]]
name = "jsx"
injection-regex = "(jsx|react|react-native)"
language-id = "javascript"
language-servers = ["typescript-language-server"]
grammar = "javascript"

[[language]]
name = "tsx"
injection-regex = "(tsx|react|react-native)"
language-id = "typescript"
language-servers = ["typescript-language-server"]
grammar = "typescript"

# CSS CONFIGURATION
[[language]]
name = "css"
language-servers = [ "vscode-css-language-server" ]
auto-format = true

[[language]]
name = "yaml"
auto-format = true
language-servers = ["yaml-language-server"]
