# GOLANG CONFIGURATION
[[language]]
name = "go"
formatter = { command = "goimport" }


[language-server.gopls]
command = "gopls"
args = ["-logfile=/tmp/gopls.log",  "serve"]
[language-server.gopls.config]
"ui.diagnostic.staticcheck" = true

[language-server.gopls.config.hints]
assignVariableTypes = true
constantValues = true
functionTypeParameters = true
parameterNames = true
rangeVariableTypes = true

# PYTHON CONFIGURATION
[[language]]
name = "python"
comment-token = "#"
language-servers = [ "pylsp" ]

# TYPESCRIPT/JS/REACT/ANYTHING JAVASCRIPT
[language-server.typescript-language-server]
command = "typescript-language-server"
args = ["--stdio"]
config.hostInfo = "helix"

[[language]]
name = "typescript"
injection-regex = "(ts|typescript)"
language-id = "typescript"
language-servers = [ "typescript-language-server"]
grammar = "typescript"

[[language]]
name = "javascript"
injection-regex = "(js|javascript)"
language-id = "javascript"
comment-token = "//"
language-servers = [ "typescript-language-server" ]
grammar = "javascript"

# REACT CONFIGURATION
[[language]]
name = "jsx"
injection-regex = "(jsx|react)"
language-id = "javascript"
language-servers = ["typescript-language-server"]
grammar = "javascript"

[[language]]
name = "tsx"
injection-regex = "(tsx|react)"
language-id = "typescript"
language-servers = ["typescript-language-server"]

# CSS CONFIGURATION
[[language]]
name = "css"
language-servers = [ "vscode-css-language-server" ]
auto-format = true

[[language]]
name = "yaml"
auto-format = true
language-servers = ["yaml-language-server"]

[[language]]
name = "svelte"
auto-format = false
language-servers = ["svelte-language-server"]

[[language]]
name = "html"
language-servers = [ "vscode-html-language-server", "tailwindcss-ls" ]

[[language]]
name = "css"
language-servers = [ "vscode-css-language-server", "tailwindcss-ls" ]

[[language]]
name = "jsx"
language-servers = [ "typescript-language-server", "tailwindcss-ls" ]

[[language]]
name = "tsx"
language-servers = [ "typescript-language-server", "tailwindcss-ls" ]

[[language]]
name = "svelte"
language-servers = [ "svelteserver", "tailwindcss-ls" ]

[language-server]
biome = { command = "biome", args = ["lsp-proxy"] }

[[language]]
name = "javascript"
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]
auto-format = true

[[language]]
name = "typescript"
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]
auto-format = true

[[language]]
name = "tsx"
auto-format = true
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]

[[language]]
name = "jsx"
auto-format = true
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]

[[language]]
name = "json"
language-servers = [ { name = "vscode-json-language-server", except-features = [ "format" ] }, "biome" ]
