# GOLANG CONFIGURATION

[language-server.gopls]
command = "gopls"
config = { "gofumpt" = true, "local" = "goimports", "semanticTokens" = true, "staticcheck" = true, "verboseOutput" = true, "analyses" = { "fieldalignment" = true, "nilness" = true, unusedparams = true, unusedwrite = true, useany = true }, usePlaceholders = true, completeUnimported = true, hints = { "assignVariableType" = true, "compositeLiteralFields" = true, "compositeLiteralTypes" = true, "constantValues" = true, "functionTypeParameters" = true, "parameterNames" = true, "rangeVariableTypes" = true } }

[[language]]
name = "go"
roots = ["go.work", "go.mod"]
auto-format = true
comment-token = "//"
language-servers = [ "gopls"]
formatter = { command = "goimports" }

# PYTHON CONFIGURATION
[[language]]
name = "python"
scope = "source.python"
injection-regex = "python"
file-types = ["py","pyi","py3","pyw",".pythonstartup",".pythonrc"]
shebangs = ["python"]
roots = [".", "pyproject.toml", "pyrightconfig.json"]
comment-token = "#"
language-servers = ["pyright", "ruff"]
indent = { tab-width = 4, unit = "    " }
auto-format = true

[language.formatter]
command = "black"
args = [
  "-",
  "--quiet",
  "--line-length=88"
]

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.pyright.config]
reportMissingTypeStubs = false

[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"
autoImportCompletions = true

[language-server.ruff]
command = "ruff-lsp"

[language-server.ruff.config]
settings = {args = []}

# TYPESCRIPT/JS/REACT/ANYTHING JAVASCRIPT
[language-server.typescript-language-server]
command = "typescript-language-server"
args = ["--stdio"]
config.hostInfo = "helix"

[[language]]
name = "typescript"
injection-regex = "(ts|typescript|tsx)"
language-id = "typescript"
language-servers = [ "typescript-language-server" ]
formatter = { command = "prettier", args = ["--parser", "html"]}
grammar = "typescript"
auto-format = false

[[language]]
name = "javascript"
injection-regex = "(js|javascript|jsx)"
language-id = "javascript"
comment-token = "//"
language-servers = [ "typescript-language-server" ]
formatter = { command = "prettier", args = ["--parser", "html"]}
grammar = "javascript"
auto-format = false

[[language]]
name = "svelte"
language-id = "svelte"
injection-regex = "(js|javascript|svelte|ts|)"
comment-token = "//"
# language-servers = [ "svelte-language-server" ]
language-servers = [ { name = "tailwindcss-language-server", except-features = ["hover"] }, "svelteserver", "emmet-ls", "eslint-ls" ]
formatter = { command = "prettier", args = ["--parser", "html"]}
auto-format = false

# CSS CONFIGURATION
[[language]]
name = "css"
language-id = "css"
language-servers = [ "vscode-css-language-server" ]
formatter = { command = "prettier", args = ["--parser", "html"]}
grammar = "svelte"
auto-format = false

# CSS CONFIGURATION
[[language]]
name = "css"
language-id = "css"
language-servers = [ "vscode-json-language-server" ]
formatter = { command = "prettier", args = ["--parser", "html"]}
grammar = "json"
auto-format = false
