# GOLANG CONFIGURATION
[[language]]
name = "go"
formatter = { command = "goimport" }

[language-server.gopls]
command = "gopls"

[language-server.gopls.config.hints]
assignVariableTypes = true
compositeLiteralFields = true
constantValues = true
functionTypeParameters = true
parameterNames = true
rangeVariableTypes = true

[language-server.golangci-lint-lsp]
command = "golangci-lint-langserver"

# PYTHON CONFIGURATION
[[language]]
name = "python"
comment-token = "#"
language-servers = [ "pylsp" ]


# TYPESCRIPT/JS/REACT/ANYTHING JAVASCRIPT
[[language]]
name = "typescript"
injection-regex = "(ts|typescript)"
language-id = "typescript"
language-servers = [ "typescript-language-server" ]


[[language]]
name = "javascript"
injection-regex = "(js|javascript)"
language-id = "javascript"
comment-token = "//"
language-servers = [ "typescript-language-server" ]

grammar = "javascript"

# CSS CONFIGURATION
[[language]]
name = "css"
language-servers = [ "vscode-css-language-server" ]
auto-format = true
