# LANGUAGE SERVERS CONFIGURATION

[language-server.astro-ls]
command = "astro-ls"
args = ["--stdio"]
config = { typescript = { tsdk = "~/.volta/tools/image/packages/typescript/lib/node_modules/typescript/lib" }, environment = "node"}

[language-server.tailwindcss-ls]
command = "tailwindcss-language-server"
args = ["--stdio"]
config = { userLanguages = { astro = "html", "*.astro" = "html" }}

[language-server.emmet-ls]
command = "emmet-language-server"
args = ["--stdio"]

# ESLint configuration
# Note: The ESLint language server is configured to use the ESLint CLI engine.
# This means it will use the ESLint configuration from your project.
# Ensure you have ESLint installed in your project.
# You can install it using npm or yarn:
# npm install eslint --save-dev
# yarn add eslint --dev
[language-server.eslint-ls]
command = "vscode-eslint-language-server"
args = ["--stdio"]

[language-server.eslint-ls.config]
validate = "on"

[language-server.eslint-ls.config.experimental]
useFlatConfig = false

# Empty array for rule customizations
language-server.eslint-ls.config.rulesCustomizations = []

[language-server.eslint-ls.config.problems]
shortenToSingleLine = false

language-server.eslint-ls.config.nodePath = ""

[language-server.eslint-ls.config.codeAction.disableRuleComment]
enable = true
location = "separateLine"

[language-server.eslint-ls.config.codeAction.showDocumentation]
enable = true

[language-server.eslint-ls.config.codeAction.onSave]
enable = true
mode = "fixAll"

[language-server.eslint-ls.config.workingDirectory]
mode = "location"

[language-server.eslint-ls.config.run]
# Note: Based on your original, you likely meant:
run = "onType"

# GO
[[language]]
name = "go"
formatter = { command = "goimports" }
language-servers = ["gopls"]

[language-server.gopls]
command = "gopls"
args = ["-logfile=/tmp/gopls.log", "serve"]

# [language-server.gopls.config]
# "ui.diagnostic.staticcheck" = true
[language-server.gopls.config.ui.diagnostic]
staticcheck = true

[language-server.gopls.config.hints]
assignVariableTypes = true
constantValues = true
functionTypeParameters = true
parameterNames = true
rangeVariableTypes = true

[debugger.dlv]
name = "dlv"
command = "dlv"
args = ["dap"]
transport = "stdio"
templates = []

# SVELTE
[[language]]
name = "svelte"
scope = "source.svelte"
injection-regex = "(svelte|.server.ts)"
file-types = ["svelte", "+page.server.ts", "+layout.server.ts", "+endpoint.ts"]
roots = ["package.json", "svelte.config.js", ".git", ".svelte-kit"]
formatter = { command = "prettier", args = ["--parser", "svelte"] }
language-servers = ["tailwindcss-ls", "svelte-language-server", "emmet-ls", "eslint-ls"]

[language-server.svelte-language-server]
command = "svelte-language-server"
args = ["--stdio"]

# TYPESCRIPT & REACT (TSX)
[[language]]
name = "typescript"
file-types = ["ts", "tsx"]
formatter = { command = "prettier", args = ["--stdin-filepath", "file.tsx"] }
language-servers = ["tailwindcss-ls", "typescript-language-server", "emmet-ls", "eslint-ls"]

[language-server.typescript-language-server]
command = "typescript-language-server"
args = ["--stdio"]

# JAVASCRIPT & REACT (JSX)
[[language]]
name = "javascript"
file-types = ["js", "jsx"]
formatter = { command = "prettier" }
language-servers = ["tailwindcss-ls", "typescript-language-server", "emmet-ls", "eslint-ls"]

# HTML
[[language]]
name = "html"
formatter = { command = "prettier" }
language-servers = ["tailwindcss-ls", "vscode-html-language-server", "emmet-ls", "eslint-ls"]

# CSS
[[language]]
name = "css"
formatter = { command = "prettier" }
language-servers = ["tailwindcss-ls", "vscode-css-language-server", "emmet-ls", "eslint-ls"]

[[language]]
name = "scss"
formatter = { command = "prettier" }
language-servers = ["tailwindcss-ls", "vscode-css-language-server", "emmet-ls", "eslint-ls"]

# FISH
[[language]]
name = "fish"
scope = "source.fish"
injection-regex = "fish"
file-types = ["fish"]
shebangs = ["fish"]
comment-token = "#"
language-servers = ["fish-lsp"]
indent = { tab-width = 4, unit = "    " }
auto-format = true
formatter = { command = "fish_indent" }

[[grammar]]
name = "fish"
source = { git = "https://github.com/ram02z/tree-sitter-fish", rev = "a78aef9abc395c600c38a037ac779afc7e3cc9e0" }

[[language]]
name = "json"
scope = "source.json"
injection-regex = "json"
file-types = ["json", "jsonl", "jsonld", { glob = ".babelrc" }, "js.map", "ts.map"]
language-servers = ["vscode-json-language-server"]
formatter = { command = "prettier", args = ["--stdin-filepath", "file.json"] }
auto-format = true
indent = { tab-width = 2, unit = "  " }

[language-server.vscode-json-language-server]
command = "vscode-json-language-server"
args = ["--stdio"]

[[language]]
name = "jsonc"
scope = "source.json"
injection-regex = "jsonc"
file-types = ["jsonc", { glob = "tsconfig.json" }, { glob = "bun.lock" }]
comment-token = "//"
block-comment-tokens = { start = "/*", end = "*/" }
grammar = "json"
language-servers = ["vscode-json-language-server"]
auto-format = true
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "json5"
scope = "source.json5"
injection-regex = "json5"
file-types = ["json5"]
language-servers = []
comment-token = "//"
indent = { tab-width = 4, unit = "    " }

[[grammar]]
name = "json"
source = { git = "https://github.com/tree-sitter/tree-sitter-json", rev = "73076754005a460947cafe8e03a8cf5fa4fa2938" }

[[grammar]]
name = "json5"
source = { git = "https://github.com/Joakker/tree-sitter-json5", rev = "c23f7a9b1ee7d45f516496b1e0e4be067264fa0d" }

# DEBUGGING
[debugger.lldb]
name = "lldb-vscode"
transport = "stdio"
command = "lldb-vscode"